get http://localhost:8888/user/all

###

post http://localhost:8888/auth/login
Content-Type: application/json

{
    "userName" : "behara.kiran"
}

###

post http://localhost:8888/masters/bloodGroups/add
Content-Type: application/json

{
    "completeName" : "A RhD positive",
    "shortName" : "A+"
}


### 

GET http://localhost:8888/masters/bloodGroups/all